excluded:
  - Pods
  - Carthage
line_length:
    warning: 120
    ignores_comments: true
    ignores_interpolated_strings: true
disabled_rules:
  - type_body_length
  - function_body_length
  - nesting
  - identifier_name
  - file_length
  - for_where
  - blanket_disable_command
