// This file is generated by generate_salesforce_services.swift and should not be modified manually.
// swiftlint:disable superfluous_disable_command type_name

import Foundation

typealias SalesforceB2CCommerceCloud =
    BaseSalesforceB2CCommerceCloud & RequiredServiceProperties & SalesforceStoreService

class BaseSalesforceB2CCommerceCloud: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "B2C_Commerce_Cloud")
    let url = URL(string: "https://status.salesforce.com/products/B2C_Commerce_Cloud")!
}

typealias SalesforceExperienceCloud =
    BaseSalesforceExperienceCloud & RequiredServiceProperties & SalesforceStoreService

class BaseSalesforceExperienceCloud: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Community_Cloud")
    let url = URL(string: "https://status.salesforce.com/products/Community_Cloud")!
}

typealias Datorama =
    BaseDatorama & RequiredServiceProperties & SalesforceStoreService

class BaseDatorama: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Datorama")
    let url = URL(string: "https://status.salesforce.com/products/Datorama")!
}

typealias Heroku =
    BaseHeroku & RequiredServiceProperties & SalesforceStoreService

class BaseHeroku: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Heroku")
    let url = URL(string: "https://status.salesforce.com/products/Heroku")!
}

typealias MCAccountEngagement =
    BaseMCAccountEngagement & RequiredServiceProperties & SalesforceStoreService

class BaseMCAccountEngagement: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "MCAccountEngagement")
    let url = URL(string: "https://status.salesforce.com/products/MCAccountEngagement")!
}

typealias MCPersonalization =
    BaseMCPersonalization & RequiredServiceProperties & SalesforceStoreService

class BaseMCPersonalization: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "MCPersonalization")
    let url = URL(string: "https://status.salesforce.com/products/MCPersonalization")!
}

typealias SalesforceMarketingCloud =
    BaseSalesforceMarketingCloud & RequiredServiceProperties & SalesforceStoreService

class BaseSalesforceMarketingCloud: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Marketing_Cloud")
    let url = URL(string: "https://status.salesforce.com/products/Marketing_Cloud")!
}

typealias Mulesoft =
    BaseMulesoft & RequiredServiceProperties & SalesforceStoreService

class BaseMulesoft: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Mulesoft")
    let url = URL(string: "https://status.salesforce.com/products/Mulesoft")!
}

typealias SalesforceServices =
    BaseSalesforceServices & RequiredServiceProperties & SalesforceStoreService

class BaseSalesforceServices: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Salesforce_Services")
    let url = URL(string: "https://status.salesforce.com/products/Salesforce_Services")!
}

typealias Spiff =
    BaseSpiff & RequiredServiceProperties & SalesforceStoreService

class BaseSpiff: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Spiff")
    let url = URL(string: "https://status.salesforce.com/products/Spiff")!
}

typealias Tableau =
    BaseTableau & RequiredServiceProperties & SalesforceStoreService

class BaseTableau: BaseSalesforceCategory {
    static var store = SalesforceStore(key: "Tableau")
    let url = URL(string: "https://status.salesforce.com/products/Tableau")!
}
